### ISSUE TITLE
in Shows admin, past broadcasts are listed incorrectly as events

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#81] opened 2015-04-14 11:06 UTC
For example: https://dev.wavefarm.org/admin/wmcyzf
All of those events are broadcasts, not calendar events.

**Comment by galenjosephhunter** [comment] 2015-04-14 11:08
Same as #31?

**Comment by galenjosephhunter** [comment] 2015-04-23 10:11
Adding Gabe's comment posted in a redundant issue in case it is helpful. 
Gabe wrote: "Broadcasts are still linked as "events" from related items. Need to fix the export and display of broadcasts in relation to shows, artists, etc."

**Comment by gsf** [comment] 2015-05-03 05:38
Should be fixed now in export. See https://code.google.com/p/free103/source/detail?r=870b367f152a46db834ad832bef0b861d1d845a5.

**Comment by galenjosephhunter** [comment] 2015-05-03 09:27
Note sure if the export already happened, but I don't this this worked yet? See:
https://dev.wavefarm.org/admin/hew98c (where all those items listed under "events" should be "broadcasts") and then on https://dev.wavefarm.org/wgxc/schedule/hew98c where as a result all related broadcasts are being listed under "TURN OUT" which should only list events. (The TUNE IN header is being used for broadcasts.)

**Comment by gsf** [comment] 2015-05-03 18:22
Yes I haven't migrated the production data to dev yet. I'll close again when I do.

**Comment by gsf** [comment] 2015-05-09 21:16
This appears to be working, though it would not appear so looking at https://dev.wavefarm.org/admin/hew98c. Most of the items under "broadcasts" are also under "events" because in the old system these events have both types "Wave Farm Radio Broadcast" and "WGXC Community Calendar Event (this event is not organized by WGXC)". A broadcast and an event have therefore been created for each of those items. Is this the expected behavior?

On a side note, the "WGXC Community Calendar Event (this event is not organized by WGXC)" type is a bit unwieldy due to its length. Could we shorten it to "WGXC Community Calendar"? If the extra info is needed, that seems like a site UI issue.

**Comment by galenjosephhunter** [comment] 2015-05-10 09:34
Yes. I can update the WGXC Community Calendar type. Do you mean literally deleting the ( ) content in free103point9.org/admin? If so, just confirm and I will do so. Do we need to alert Peter to this or will this not impact his code for wgxc/calendar.

**Comment by galenjosephhunter** [comment] 2015-05-10 09:39
There does seem to be something additional at play her though. Look at this example:
http://old.free103point9.org/admin/events/event/13758/
This is a broadcast event called "Zoom: Mail Order Monsters" in the current admin. The only type attached to this event in the current admin is WGXC 90.7-FM Broadcast.

Now look at the show record for "Zoom" in the new admin https://dev.wavefarm.org/admin/wmcyzf
You will see that "Zoom: Mail Order Monsters" is listed both as a broadcast and an event, when it should just be a broadcast.

If you click on the broadcast listing you correctly get the broadcast admin page.

If you click on the event listing https://dev.wavefarm.org/admin/sz33mt you get a blank admin page.

On the front end this broadcast correctly only shows up under TUNE IN. 

So the question is why is it listed under "events" in admin?

**Comment by gsf** [comment] 2015-05-13 05:34
We'll see if the fix at https://code.google.com/p/free103/source/detail?r=bb18ec85e5dd03c42b995737468c7b29cb78d438 does the trick.

**Comment by gsf** [comment] 2015-05-13 13:44
That appears to have worked. See https://dev.wavefarm.org/admin/wmcyzf.

**Closed by gsf** 2015-05-13 13:44 UTC

**Comment by galenjosephhunter** [comment] 2015-05-13 13:52
Excellent!


Galen Joseph-Hunter
Executive Director
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>
