### ISSUE TITLE
Unable to add more than one artist to a broadcast

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#85] opened 2015-04-20 14:41 UTC
This is related to the difficulty in adding artists, and other related material, but I don't seem to be able to add more than one artist. I'm trying to add a broadcast right now and can (with some difficulty) add an artist, but as soon as I try to add an additional, the first disappears.

**Comment by galenjosephhunter** [comment] 2015-05-01 18:30
same as #86?

**Comment by gsf** [comment] 2015-05-02 18:47
Yes, duplicate of #86.

**Closed by gsf** 2015-05-02 18:47 UTC
