### ISSUE TITLE
Possible issue with duplicate broadcasts displaying at 

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#87] opened 2015-04-24 09:44 UTC
There are a bunch if duplicates displaying for Saturday (4/25) at https://wavefarm.org/wgxc/schedule
Because data is not recent on dev. I can't really tell if this is a current issue or not. I think it might only be broadcasts that are also wavefarmradio broadcasts displaying in duplicate, so not sure if this is Gabe or Peter...

**Comment by galenjosephhunter** [comment] 2015-04-25 11:18
so it appears that the duplication is happening as part of the data migration. Look at 
https://dev.wavefarm.org/wgxc/schedule/2015-04-25
and
https://dev.wavefarm.org/admin/?q=type%3Abroadcast+meza

**Comment by galenjosephhunter** [comment] 2015-04-28 09:05
hmm.. so I was just looking back at https://dev.wavefarm.org/wgxc/schedule/2015-04-25 and now the duplications are gone. but there is a duplication currently on https://wavefarm.org/wgxc/schedule/2015-04-28 (today's date). It might be that duplications are only appearing on the current and future dates and disappear once the date has passed.

**Comment by gsf** [comment] 2015-05-03 00:31
I think this was caused by the lack of a "distinct" on the broadcast queryset. Should be fixed with https://code.google.com/p/free103/source/detail?r=468798a563920446bec69f0d88c2a4212a094d55. Please reopen if the next migration doesn't confirm.

**Closed by gsf** 2015-05-03 00:31 UTC

**Comment by galenjosephhunter** [comment] 2015-05-04 09:44
Seems to have worked! Thank you!
